version: '3'

services:
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GUID: ${GUID:-1000}
        TZ: ${TZ:-Europe/Moscow}
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - "./:/var/www/app:ro"
      - "./docker/web/vhost.conf:/etc/nginx/conf.d/default.conf:ro"
    env_file:
      - .env.default
      - .env

  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GUID: ${GUID:-1000}
        TZ: ${TZ:-Europe/Moscow}
    volumes:
      - "./:/var/www/app"
    env_file:
      - .env.default
      - .env

  db:
    image: mariadb:latest
    restart: always
    volumes:
      - "db_data:/var/lib/mysql"
    ports:
      - ${DOCKER_DB_PORT:-3306}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-laravel}
      MYSQL_RANDOM_ROOT_PASSWORD: 1

  memcached:
    image: memcached
    restart: always

volumes:
  db_data:
    driver: local
